In [1]:
import pandas as pd
import pickle
from utils import model as mod

In [2]:
df = pd.read_pickle('../data/03_df_data')
segs = pd.read_pickle('../data/02_df_seg_race')

with open("../data/02_dic_ref_groups.pkl", "rb") as file:
    ref_groups = pickle.load(file)

In [3]:
df.head()

,loan_type,loan_purpose,preapproval,construction_method,occupancy_type,loan_amount,action_taken,state_code,county_code,census_tract,...,interest_only_payment,property_value,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,open_end_line_of_credit,business_or_commercial_purpose,reg_uw,denied,reg_price
1,Conventional,Home purchase,Not requested,Site built,Primary residence,1205000,Purchased,WA,53033.0,53033032318.0,...,Not interest only,1505000.0,Not applicable,Not applicable,1,Not open end credit,Not business commercial,0,0,0
2,Conventional,Home purchase,Not requested,Site built,Primary residence,925000,Purchased,WA,53011.0,53011040303.0,...,Not interest only,1035000.0,Not applicable,Not applicable,1,Not open end credit,Not business commercial,0,0,0
5,Conventional,Home purchase,Not requested,Site built,Primary residence,905000,Purchased,WA,53011.0,53011040905.0,...,Not interest only,1135000.0,Not applicable,Not applicable,1,Not open end credit,Not business commercial,0,0,0
13,Conventional,Home purchase,Not requested,Site built,Second residence,1505000,Purchased,CA,6065.0,6065045606.0,...,Not interest only,4295000.0,Not applicable,Not applicable,1,Not open end credit,Not business commercial,0,0,0
14,Conventional,Home purchase,Not requested,Site built,Investment,605000,Purchased,CA,6059.0,6059062641.0,...,Not interest only,1645000.0,Not applicable,Not applicable,1,Not open end credit,Business commercial,0,0,0

In [4]:
segs

,loan_type,loan_purpose,applicant_race_1,applied,event_count,event_rate,mi_rate,mu_rate,mx_rate,crit event,crit count
1,Conventional,Cash out refinance,Black African American,1761,257,0.145940,4.490,6.737013,9.740,True,True
2,Conventional,Cash out refinance,White,9223,1274,0.138133,2.875,6.765602,10.240,True,True
4,Conventional,Home improvement,Black African American,541,128,0.236599,4.750,7.659269,10.240,True,True
5,Conventional,Home improvement,White,3644,669,0.183589,4.625,7.822651,10.240,True,True
6,Conventional,Home purchase,Asian,6913,458,0.066252,2.625,6.136274,8.990,True,True
7,Conventional,Home purchase,Black African American,4818,502,0.104193,2.500,6.380016,9.240,True,True
8,Conventional,Home purchase,White,36101,2336,0.064707,1.000,6.375974,9.490,True,True
9,Conventional,Refinance,Asian,1701,137,0.080541,3.750,5.902198,8.030,True,True
11,Conventional,Refinance,White,7497,559,0.074563,4.250,6.179631,8.375,True,True
18,FHA insured,Home purchase,Black African American,884,125,0.141403,4.125,6.339181,7.750,True,True
19,FHA insured,Home purchase,White,2250,210,0.093333,3.750,6.295870,7.750,True,True

In [5]:
testing = segs.columns.tolist()[2]

In [6]:
ref_groups

{'applicant_race_1': 'White',
 'applicant_sex': 'Male',
 'applicant_age_above_62': 'No'}

In [7]:
segs.loan_type.unique().tolist()

['Conventional', 'FHA insured']

 2   county_code                       7455 non-null   float64
 3   census_tract                      7455 non-null   float64

In [8]:
drop_this = [
    'applicant_ethnicity_1',        
    'applicant_race_1',                  
    'applicant_sex', 
    'applicant_age_above_62'
]

In [11]:
# %%capture output

for type_i in segs.loan_type.unique().tolist():
    print(f'\nType: {type_i}')
    
    for purp_i in segs[segs['loan_type'] == type_i].loan_purpose.unique().tolist():
        print(f'\n Purpose: {purp_i}')

        group_list = segs[(segs['loan_type'] == type_i)&(segs['loan_purpose'] == purp_i)][testing].unique().tolist()
        group_list.remove(ref_groups[testing])
        for group_i in group_list:
            print(f'\n  PB: {group_i}')
            print(f'  Ref: {ref_groups[testing]}')
    
            """
            Underwriting
            """

            print('\nUnderwriting')
    
            df_tmp = df[
                (df.loan_type == type_i) &
                (df.loan_purpose == purp_i) &
                (df[testing].isin([ref_groups[testing]] +  [group_i])) &
                (df['reg_uw'] == 1)
            ]



            
            
            print(f'shape: {df_tmp.shape}')

            print(df_tmp.groupby(testing).agg(
                count=('denied','size'),
                event_count=('denied','sum')
            ))

            # make dummy for protected basis group

            df_tmp[group_i] = (df_tmp[testing] == group_i).astype(int)

            df_tmp.drop(columns = drop_this, inplace = True)
            
            # drop columns with single value. will end up being things like indicator for segment
            df_tmp = df_tmp.loc[:, df_tmp.nunique(dropna=False) > 1]
            

            print('')
            print(df_tmp[group_i].value_counts())
            
            """
            UW Model 0
            """

            print('\nModel 0')
            
            import statsmodels.api as sm
            
            X = sm.add_constant(df_tmp[group_i])
            y = df_tmp["denied"]
            
            
            model = sm.Logit(y, X)
            result = model.fit()
            
            print(result.summary())
    
    
            
            """
            UW Model 1
            """
            print('\nModel 1')

            result = mod.logistic_woe_run(df_tmp,group_i)
            
            
            """
            UW Model 2
            """
            print('\nModel 2')

            df_tmp_psa = mod.make_match_pair(df_tmp,'denied',group_i)
            
            result = mod.logistic_woe_run(df_tmp_psa,group_i)











            
            
    
            """
            Pricing
            """
            print('\nPricing')
                
            df_tmp = df[
                (df.loan_type == type_i) &
                (df.loan_purpose == purp_i) &
                (df[testing].isin([ref_groups[testing]] +  [group_i])) &
                (df['reg_price'] == 1)
            ]



            
            
            print(f'shape: {df_tmp.shape}')

            # make dummy for protected basis group

            df_tmp[group_i] = (df_tmp[testing] == group_i).astype(int)

            df_tmp.drop(columns = drop_this, inplace = True)
            
            # drop columns with single value. will end up being things like indicator for segment
            df_tmp = df_tmp.loc[:, df_tmp.nunique(dropna=False) > 1]
            

            print('')
            print(df_tmp[group_i].value_counts())
    
            
            """
            Pri Model 0
            """
            print('\nModel 0')
            
            import statsmodels.api as sm
            
            X = sm.add_constant(df_tmp[group_i])
            y = df_tmp["interest_rate"]
            
            
            model = sm.OLS(y, X)
            result = model.fit()
            
            print(result.summary())
    
    
    
    
            
            """
            Pri Model 1
            """
            print('\nModel 1')

            result = mod.ols_dummy_run(df_tmp,group_i)

            print(result.summary())

            
    
            """
            Pri Model 2
            """

            print('\nModel 2')

            #pair function needs to ignore something, gets excluded later bc singular value
            df_tmp['rnd'] = 999
            df_tmp['action_taken'] = 'junk'
            
            df_tmp_psa = mod.make_match_pair(df_tmp,'rnd',group_i)
            result = mod.ols_dummy_run(df_tmp_psa,group_i)

            print(result.summary())

            
            
            break # group_i

        break # purp_i
    break # type_i

with open("regression analysis output.txt", "w") as f:
    f.write(output.stdout)
    f.write(output.stderr)

In [ ]:
print(
    'hello'
)

def ols_dummy_run(df_tmp):
    import numpy as np
    import pandas as pd
    
    # df_tmp.info()
    
    # drop denied
    df_tmp.drop(columns=['action_taken'], inplace= True)
    
    # check unique values in characaters. we cant have too many and end up losing dfs
    
    def remove_high_cardinality_text_columns(df, max_cnt):
        """
        Remove object and string columns with more than max_cnt
        unique values.
    
        Returns:
            cleaned_df, unique_counts, removed_columns
        """
        text_cols = df.select_dtypes(
            include=["object", "str"]
        ).columns
    
        unique_counts = df[text_cols].nunique()
    
        removed_columns = unique_counts[
            unique_counts > max_cnt
        ].index.tolist()
    
        cleaned_df = df.drop(columns=removed_columns)
    
        return cleaned_df, unique_counts, removed_columns
    
    
    df_tmp, counts, removed = remove_high_cardinality_text_columns(
        df_tmp,
        max_cnt=20
    )
    
    # print(counts)
    print("Removed columns:", removed)
    
    
    
    # create bins for numerics
    
    
    import pandas as pd
    
    def qcut_numeric_columns(df, n_bins=5, exclude_cols=None):
        df = df.copy()
    
        if exclude_cols is None:
            exclude_cols = []
    
        numeric_cols = [
            col for col in df.select_dtypes(include="number").columns
            if col not in exclude_cols
        ]
    
        for col in numeric_cols:
            df[col] = (
                pd.qcut(
                    df[col],
                    q=n_bins,
                    labels=False,
                    duplicates="drop"
                )
                .add(1)
                .astype("object")
                .fillna("missing")
            )
    
        return df
    
    
    df_tmp = qcut_numeric_columns(
        df_tmp,
        n_bins=5,
        exclude_cols=["interest_rate", group_i]
    )
    
    
    
    # df_tmp.head()
    
    # df_tmp.info()
    
    
    
    # make dummy vars
    
    df_tmp = pd.get_dummies(
        df_tmp,
        columns=df_tmp.select_dtypes(exclude="number").columns,
        drop_first=True,
        dtype=int
    )
    
    df_tmp.shape
    
    ####### assign x and y data
    y = df_tmp["interest_rate"]
    
    # drop columns with single value. will end up being things like indicator for segment
    df_tmp = df_tmp.loc[:, df_tmp.nunique(dropna=False) > 1]
    

    
    
    
    # reorder columns
    col_order = df_tmp.columns.tolist()
    col_order.remove(group_i)
    df_tmp = df_tmp[[group_i] + col_order]
    
    X = sm.add_constant(df_tmp.drop(columns='interest_rate'))


    # Duplicate columns
    duplicate_cols = X.columns[X.T.duplicated()].tolist()
    print("Duplicate columns:", duplicate_cols)
    
    # Constant columns
    constant_cols = X.columns[X.nunique() <= 1].tolist()
    print("Constant columns:", constant_cols)
    
    # Matrix rank
    print("Number of columns:", X.shape[1])
    print("Matrix rank:", np.linalg.matrix_rank(X.to_numpy()))
    
    # do if duplicates then drop them
    
    if len(duplicate_cols) > 0:
        X = X.drop(columns=constant_cols + duplicate_cols)

    
    # drop high corr
    
    import numpy as np
    
    corr = X.corr().abs()
    
    upper = corr.where(
        np.triu(np.ones(corr.shape), k=1).astype(bool)
    )
    
    to_drop = [
        column
        for column in upper.columns
        if any(upper[column] > 0.95)
    ]
    
    X = X.drop(columns=to_drop)
    
    print("Dropped columns:", to_drop)
    
    
    
    
    
    
    model = sm.OLS(y, X)
    result = model.fit()
    
    # print(result.summary())

    return result

import numpy as np


def make_match_pair(df_tmp, target_to_exclude):
    
    from psmpy import PsmPy
    from psmpy.functions import cohenD
    # from psmpy.plotting import *
    
    # redo this but wit the pre woe data. need to redo woe before matched pair reg
    # df_tmp
    # df_tmp_woe
    
    
    # df_tmp_woe["row_id"] = df_tmp_woe.index
    df_tmp["row_id"] = df_tmp.index
    
    # df_tmp.head()
    
    # need to make dummies
    df_tmp_4psa = df_tmp
    
    
    
    exclude = [target_to_exclude, group_i, 'row_id']
    
    df_tmp_4psa = pd.concat(
        [
            df_tmp_4psa[exclude],
            pd.get_dummies(df_tmp_4psa.drop(columns=exclude), dtype=int)
        ],
        axis=1
    )
    
    
    
    
    # df_tmp_4psa.info()
    
    missing_columns = df_tmp_4psa.columns[df_tmp_4psa.isna().any()].tolist()
    missing_columns
    
    # target_to_exclude + missing_columns
    
    
    
    # psm = PsmPy(df_tmp_woe, treatment=group_i, indx='row_id', exclude = ['denied'])
    psm = PsmPy(df_tmp_4psa, treatment=group_i, indx='row_id', exclude = [target_to_exclude] + missing_columns)
    
    psm.logistic_ps(balance = True)
    
    psm.kdtree_matched(matcher='propensity_logit', replacement=False, caliper=None, drop_unmatched=True)
    
    # psm.df_matched
    
    # get unbinned attributes 
    # df_tmp_psa = pd.concat([], axis=1)
    df_tmp_psa = pd.DataFrame(psm.df_matched['row_id']).merge(df_tmp, on="row_id", how="left")
    df_tmp_psa.drop(columns='row_id', inplace = True)
    
    # df_tmp_psa.head()

    return df_tmp_psa



def logistic_woe_run(df_tmp):
    
    # check separtion and remove those columns
    flagged_variables = mod.find_separation_variables(
        df=df_tmp,
        target="denied",
        print_results=False,
        check_near_separation=True
    )
    
    df_tmp.drop(columns = flagged_variables, inplace = True)
    
    
    #############create woe
    import toad
    
    # Ensure object columns are clean strings
    object_cols = df_tmp.select_dtypes(include=["object", "string"]).columns
    
    for col in object_cols:
        df_tmp[col] = df_tmp[col].astype("string").fillna("__MISSING__")
    
    
    
    # Create the combiner
    combiner = toad.transform.Combiner()
    
    # Fit bins 
    combiner.fit(
        df_tmp,
        y='denied',
        method="chi",
        min_samples=0.05,
        exclude= [group_i]   #['denied']
    )
    
    # Apply bin rules
    df_tmp_bin = combiner.transform(df_tmp)
    
    # convert bins to woe 
    woe_transformer = toad.transform.WOETransformer()
    
    df_tmp_woe = woe_transformer.fit_transform(
        df_tmp_bin,
        df_tmp_bin['denied'],
        exclude=['denied',group_i]
    )
    
    
    ####### assign x and y data
    y = df_tmp_woe["denied"]
    
    # drop columns with single value. will end up being things like indicator for segment
    df_tmp_woe = df_tmp_woe.loc[:, df_tmp_woe.nunique(dropna=False) > 1]
    
    # reorder columns
    col_order = df_tmp_woe.columns.tolist()
    col_order.remove(group_i)
    df_tmp_woe = df_tmp_woe[[group_i] + col_order]
    
    X = sm.add_constant(df_tmp_woe.drop(columns='denied'))
   
    model = sm.Logit(y, X)
    result = model.fit()
    
    print(result.summary())

    return result