In [1]:
import pandas as pd
import pickle
from utils import model as mod

In [2]:
df = pd.read_pickle('../data/03_df_data')
segs = pd.read_pickle('../data/02_df_seg_race')

with open("../data/02_dic_ref_groups.pkl", "rb") as file:
    ref_groups = pickle.load(file)

In [3]:
df.head()

,loan_type,loan_purpose,preapproval,construction_method,loan_amount,action_taken,state_code,county_code,census_tract,applicant_ethnicity_1,...,intro_rate_period,balloon_payment,interest_only_payment,property_value,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,reg_uw,denied,reg_price
1,Conventional,Home purchase,Not requested,Site built,1205000,Purchased,WA,53033.0,53033032318.0,Not Hispanic Latino,...,NaN,No balloon,Not interest only,1505000.0,Not applicable,Not applicable,1,0,0,0
2,Conventional,Home purchase,Not requested,Site built,925000,Purchased,WA,53011.0,53011040303.0,Info not provided,...,NaN,No balloon,Not interest only,1035000.0,Not applicable,Not applicable,1,0,0,0
5,Conventional,Home purchase,Not requested,Site built,905000,Purchased,WA,53011.0,53011040905.0,Not Hispanic Latino,...,NaN,No balloon,Not interest only,1135000.0,Not applicable,Not applicable,1,0,0,0
13,Conventional,Home purchase,Not requested,Site built,1505000,Purchased,CA,6065.0,6065045606.0,Not Hispanic Latino,...,NaN,No balloon,Not interest only,4295000.0,Not applicable,Not applicable,1,0,0,0
15,Conventional,Refinance,Not requested,Site built,1145000,Purchased,WA,53033.0,53033002700.0,Info not provided,...,84.0,No balloon,Not interest only,1725000.0,Not applicable,Not applicable,1,0,0,0

In [4]:
segs

,loan_type,loan_purpose,applicant_race_1,applied,event_count,event_rate,mi_rate,mu_rate,mx_rate,crit event,crit count
0,Conventional,Cash out refinance,Black African American,1607,218,0.135657,4.490,6.720161,9.74,True,True
1,Conventional,Cash out refinance,White,8725,1163,0.133295,2.875,6.756857,10.24,True,True
4,Conventional,Home purchase,Black African American,4562,458,0.100395,2.500,6.358342,9.24,True,True
5,Conventional,Home purchase,White,34364,2132,0.062042,1.000,6.356195,9.49,True,True
12,FHA insured,Home purchase,Black African American,883,124,0.140430,4.125,6.339181,7.75,True,True
13,FHA insured,Home purchase,White,2250,210,0.093333,3.750,6.295870,7.75,True,True

In [5]:
testing = segs.columns.tolist()[2]
testing

'applicant_race_1'

In [6]:
ref_groups

{'applicant_race_1': 'White',
 'applicant_sex': 'Male',
 'applicant_age_above_62': 'No'}

In [7]:
segs.loan_type.unique().tolist()

['Conventional', 'FHA insured']

 2   county_code                       7455 non-null   float64
 3   census_tract                      7455 non-null   float64

In [8]:
drop_this = [
    'applicant_ethnicity_1',        
    'applicant_race_1',                  
    'applicant_sex', 
    'applicant_age_above_62'
]

In [9]:
# %%capture output

for type_i in segs.loan_type.unique().tolist():
    print(f'\nType: {type_i}')
    
    for purp_i in segs[segs['loan_type'] == type_i].loan_purpose.unique().tolist():
        print(f'\n Purpose: {purp_i}')

        group_list = segs[(segs['loan_type'] == type_i)&(segs['loan_purpose'] == purp_i)][testing].unique().tolist()
        group_list.remove(ref_groups[testing])
        for group_i in group_list:
            print(f'\n  PB: {group_i}')
            print(f'  Ref: {ref_groups[testing]}')
    
            """
            Underwriting
            """

            print('\nUnderwriting')
    
            df_tmp = df[
                (df.loan_type == type_i) &
                (df.loan_purpose == purp_i) &
                (df[testing].isin([ref_groups[testing]] +  [group_i])) &
                (df['reg_uw'] == 1)
            ]



            
            
            print(f'shape: {df_tmp.shape}')

            print(df_tmp.groupby(testing).agg(
                count=('denied','size'),
                event_count=('denied','sum')
            ))

            # make dummy for protected basis group

            df_tmp[group_i] = (df_tmp[testing] == group_i).astype(int)

            df_tmp.drop(columns = drop_this, inplace = True)
            
            # drop columns with single value. will end up being things like indicator for segment
            df_tmp = df_tmp.loc[:, df_tmp.nunique(dropna=False) > 1]
            

            print('')
            print(df_tmp[group_i].value_counts())
            
            """
            UW Model 0
            """

            print('\nModel 0')
            
            import statsmodels.api as sm
            
            X = sm.add_constant(df_tmp[group_i])
            y = df_tmp["denied"]
            
            
            model = sm.Logit(y, X)
            result = model.fit()
            
            print(result.summary())
    
    
            
            """
            UW Model 1
            """
            print('\nModel 1')

            result = mod.logistic_woe_run(df_tmp,group_i)
            
            
            """
            UW Model 2
            """
            print('\nModel 2')

            df_tmp_psa = mod.make_match_pair(df_tmp,'denied',group_i)
            
            result = mod.logistic_woe_run(df_tmp_psa,group_i)











            
            
    
            """
            Pricing
            """
            print('\nPricing')
                
            df_tmp = df[
                (df.loan_type == type_i) &
                (df.loan_purpose == purp_i) &
                (df[testing].isin([ref_groups[testing]] +  [group_i])) &
                (df['reg_price'] == 1)
            ]



            
            
            print(f'shape: {df_tmp.shape}')

            # make dummy for protected basis group

            df_tmp[group_i] = (df_tmp[testing] == group_i).astype(int)

            df_tmp.drop(columns = drop_this, inplace = True)
            
            # drop columns with single value. will end up being things like indicator for segment
            df_tmp = df_tmp.loc[:, df_tmp.nunique(dropna=False) > 1]
            

            print('')
            print(df_tmp[group_i].value_counts())
    
            
            """
            Pri Model 0
            """
            print('\nModel 0')
            
            import statsmodels.api as sm
            
            X = sm.add_constant(df_tmp[group_i])
            y = df_tmp["interest_rate"]
            
            
            model = sm.OLS(y, X)
            result = model.fit()
            
            print(result.summary())
    
    
    
    
            
            """
            Pri Model 1
            """
            print('\nModel 1')

            result = mod.ols_dummy_run(df_tmp,group_i)

            print(result.summary())

            
    
            """
            Pri Model 2
            """

            print('\nModel 2')

            #pair function needs to ignore something, gets excluded later bc singular value
            df_tmp['rnd'] = 999
            df_tmp['action_taken'] = 'junk'
            
            df_tmp_psa = mod.make_match_pair(df_tmp,'rnd',group_i)
            result = mod.ols_dummy_run(df_tmp_psa,group_i)

            print(result.summary())

            
            
    #         break # group_i

    #     break # purp_i
    # break # type_i

Type: Conventional

 Purpose: Cash out refinance

  PB: Black African American
  Ref: White

Underwriting
shape: (7003, 37)
                        count  event_count
applicant_race_1
Black African American   1044          218
White                    5959         1163

Black African American
0    5959
1    1044
Name: count, dtype: int64

Model 0
Optimization terminated successfully.
         Current function value: 0.496424
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                 denied   No. Observations:                 7003
Model:                          Logit   Df Residuals:                     7001
Method:                           MLE   Df Model:                            1
Date:                Tue, 15 Sep 2026   Pseudo R-squ.:               0.0001485
Time:                        20:40:50   Log-Likelihood:                -3476.5
converged:                       True   LL-Null:                       -3477.0
Covariance Type:            nonrobust   LLR p-value:                    0.3096
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                     -1.4168      0.033    -43.346      0.000      -1.481      -1.353
Black African American     0.0847      0.083      1.022      0.307      -0.078       0.247
==========================================================================================

Model 1
Removed constant columns: []
Removed dependent columns: []
Optimization terminated successfully.
         Current function value: 0.347370
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                 denied   No. Observations:                 7003
Model:                          Logit   Df Residuals:                     6993
Method:                           MLE   Df Model:                            9
Date:                Tue, 15 Sep 2026   Pseudo R-squ.:                  0.3004
Time:                        20:40:52   Log-Likelihood:                -2432.6
converged:                       True   LL-Null:                       -3477.0
Covariance Type:            nonrobust   LLR p-value:                     0.000
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                     -1.4153      0.042    -33.516      0.000      -1.498      -1.333
Black African American     0.1537      0.102      1.502      0.133      -0.047       0.354
loan_amount               -0.0341      0.248     -0.137      0.891      -0.521       0.453
income                     0.8307      0.097      8.563      0.000       0.641       1.021
lien_status                1.2369      0.428      2.886      0.004       0.397       2.077
debt_to_income_ratio       0.9814      0.040     24.592      0.000       0.903       1.060
loan_term                  0.5299      0.167      3.171      0.002       0.202       0.858
intro_rate_period          0.9032      0.470      1.920      0.055      -0.019       1.825
interest_only_payment     -1.4929      0.655     -2.280      0.023      -2.776      -0.209
property_value             0.4429      0.183      2.424      0.015       0.085       0.801
==========================================================================================

Model 2
Removed constant columns: []
Removed dependent columns: []
Optimization terminated successfully.
         Current function value: 0.349617
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                 denied   No. Observations:                 2088
Model:                          Logit   Df Residuals:                     2080
Method:                           MLE   Df Model:                            7
Date:                Tue, 15 Sep 2026   Pseudo R-squ.:                  0.2883
Time:                        20:40:54   Log-Likelihood:                -730.00
converged:                       True   LL-Null:                       -1025.7
Covariance Type:            nonrobust   LLR p-value:                1.719e-123
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                     -1.4868      0.100    -14.833      0.000      -1.683      -1.290
Black African American     0.1339      0.137      0.977      0.329      -0.135       0.403
loan_amount                0.6442      0.212      3.045      0.002       0.230       1.059
income                    -1.0651      1.872     -0.569      0.569      -4.735       2.605
debt_to_income_ratio       0.9922      0.066     15.119      0.000       0.864       1.121
loan_term                  0.4130      0.430      0.960      0.337      -0.430       1.256
intro_rate_period          0.5084      0.360      1.410      0.158      -0.198       1.215
property_value            -0.4134      0.377     -1.097      0.272      -1.152       0.325
==========================================================================================

Pricing
shape: (5622, 37)

Black African American
0    4796
1     826
Name: count, dtype: int64

Model 0
                            OLS Regression Results
==============================================================================
Dep. Variable:          interest_rate   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     3.134
Date:                Tue, 15 Sep 2026   Prob (F-statistic):             0.0767
Time:                        20:40:54   Log-Likelihood:                -6654.9
No. Observations:                5622   AIC:                         1.331e+04
Df Residuals:                    5620   BIC:                         1.333e+04
Df Model:                           1
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                      6.7857      0.011    594.435      0.000       6.763       6.808
Black African American    -0.0527      0.030     -1.770      0.077      -0.111       0.006
==============================================================================
Omnibus:                      559.063   Durbin-Watson:                   1.308
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              905.472
Skew:                           0.720   Prob(JB):                    2.39e-197
Kurtosis:                       4.339   Cond. No.                         2.89
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Model 1
Removed columns: ['state_code', 'county_code', 'census_tract']
Duplicate columns: ['origination_charges_missing']
Constant columns: ['const']
Number of columns: 53
Matrix rank: 52
Dropped columns: []
                                 OLS Regression Results
=======================================================================================
Dep. Variable:          interest_rate   R-squared (uncentered):                   0.992
Model:                            OLS   Adj. R-squared (uncentered):              0.992
Method:                 Least Squares   F-statistic:                          1.409e+04
Date:                Tue, 15 Sep 2026   Prob (F-statistic):                        0.00
Time:                        20:40:54   Log-Likelihood:                         -5091.7
No. Observations:                5622   AIC:                                  1.029e+04
Df Residuals:                    5571   BIC:                                  1.062e+04
Df Model:                          51
Covariance Type:            nonrobust
==================================================================================================================
                                                     coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
Black African American                             0.0200      0.023      0.866      0.386      -0.025       0.065
loan_amount_2                                      0.0371      0.024      1.531      0.126      -0.010       0.085
loan_amount_3                                      0.0479      0.036      1.350      0.177      -0.022       0.118
income_2.0                                         0.0022      0.022      0.099      0.921      -0.041       0.045
income_3.0                                         0.0097      0.028      0.345      0.730      -0.045       0.065
income_missing                                     0.0004      0.077      0.005      0.996      -0.150       0.151
rate_spread_2.0                                    0.5917      0.020     29.065      0.000       0.552       0.632
rate_spread_3.0                                    1.1319      0.023     49.803      0.000       1.087       1.176
rate_spread_missing                                0.5907      0.356      1.660      0.097      -0.107       1.288
hoepa_status_Not high cost                         2.5781      0.038     68.656      0.000       2.504       2.652
lien_status_Subordinate lien                       1.0595      0.066     16.055      0.000       0.930       1.189
applicant_credit_scoring_model_Experian FICO       0.0694      0.020      3.490      0.000       0.030       0.108
applicant_credit_scoring_model_FICO Classic 04     0.1074      0.019      5.666      0.000       0.070       0.145
total_loan_costs_2.0                               0.1135      0.027      4.187      0.000       0.060       0.167
total_loan_costs_3.0                               0.1299      0.041      3.173      0.002       0.050       0.210
total_loan_costs_missing                           2.8187      0.046     61.658      0.000       2.729       2.908
origination_charges_2.0                            0.1059      0.032      3.306      0.001       0.043       0.169
origination_charges_3.0                            0.0450      0.050      0.906      0.365      -0.052       0.142
discount_points_2.0                               -0.0079      0.031     -0.255      0.799      -0.068       0.053
discount_points_3.0                               -0.0796      0.048     -1.664      0.096      -0.173       0.014
discount_points_missing                            0.3548      0.029     12.187      0.000       0.298       0.412
lender_credits_2.0                                 0.2809      0.044      6.452      0.000       0.196       0.366
lender_credits_3.0                                 0.3456      0.042      8.144      0.000       0.262       0.429
lender_credits_missing                             0.3560      0.030     11.802      0.000       0.297       0.415
debt_to_income_ratio_30%-<36%                      0.1938      0.029      6.748      0.000       0.137       0.250
debt_to_income_ratio_36                            0.2132      0.046      4.667      0.000       0.124       0.303
debt_to_income_ratio_37                            0.2234      0.045      4.974      0.000       0.135       0.311
debt_to_income_ratio_38                            0.2142      0.045      4.798      0.000       0.127       0.302
debt_to_income_ratio_39                            0.1808      0.043      4.159      0.000       0.096       0.266
debt_to_income_ratio_40                            0.2257      0.043      5.289      0.000       0.142       0.309
debt_to_income_ratio_41                            0.2746      0.039      7.082      0.000       0.199       0.351
debt_to_income_ratio_42                            0.2801      0.039      7.237      0.000       0.204       0.356
debt_to_income_ratio_43                            0.1997      0.040      5.019      0.000       0.122       0.278
debt_to_income_ratio_44                            0.2302      0.036      6.385      0.000       0.160       0.301
debt_to_income_ratio_45                            0.2638      0.044      6.023      0.000       0.178       0.350
debt_to_income_ratio_46                            0.2019      0.057      3.555      0.000       0.091       0.313
debt_to_income_ratio_47                            0.1267      0.059      2.159      0.031       0.012       0.242
debt_to_income_ratio_48                            0.1946      0.054      3.579      0.000       0.088       0.301
debt_to_income_ratio_49                            0.2772      0.042      6.632      0.000       0.195       0.359
debt_to_income_ratio_50%-60%                       0.7030      0.177      3.974      0.000       0.356       1.050
debt_to_income_ratio_<20%                          0.1675      0.045      3.714      0.000       0.079       0.256
debt_to_income_ratio_>60%                         -0.0244      0.427     -0.057      0.954      -0.861       0.812
combined_loan_to_value_ratio_2                     0.2094      0.023      9.269      0.000       0.165       0.254
combined_loan_to_value_ratio_3                     0.3790      0.027     14.268      0.000       0.327       0.431
intro_rate_period_missing                          0.3643      0.056      6.455      0.000       0.254       0.475
interest_only_payment_Not interest only            2.0935      0.066     31.503      0.000       1.963       2.224
property_value_2                                   0.1384      0.024      5.825      0.000       0.092       0.185
property_value_3                                   0.2351      0.033      7.144      0.000       0.171       0.300
total_units_2                                     -0.1227      0.069     -1.784      0.074      -0.257       0.012
total_units_3                                      0.0100      0.171      0.058      0.953      -0.325       0.345
total_units_4                                     -0.5249      0.604     -0.868      0.385      -1.710       0.660
==============================================================================
Omnibus:                     1685.367   Durbin-Watson:                   1.729
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11150.927
Skew:                           1.266   Prob(JB):                         0.00
Kurtosis:                       9.418   Cond. No.                         174.
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Model 2
Removed columns: ['state_code', 'county_code', 'census_tract']
Duplicate columns: ['origination_charges_missing']
Constant columns: ['const']
Number of columns: 52
Matrix rank: 51
Dropped columns: []
                                 OLS Regression Results
=======================================================================================
Dep. Variable:          interest_rate   R-squared (uncentered):                   0.993
Model:                            OLS   Adj. R-squared (uncentered):              0.993
Method:                 Least Squares   F-statistic:                              4475.
Date:                Tue, 15 Sep 2026   Prob (F-statistic):                        0.00
Time:                        20:40:58   Log-Likelihood:                         -1435.6
No. Observations:                1652   AIC:                                      2971.
Df Residuals:                    1602   BIC:                                      3242.
Df Model:                          50
Covariance Type:            nonrobust
==================================================================================================================
                                                     coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
Black African American                            -0.0059      0.030     -0.201      0.841      -0.064       0.052
loan_amount_2                                     -0.0059      0.045     -0.133      0.894      -0.093       0.081
loan_amount_3                                      0.0856      0.065      1.319      0.187      -0.042       0.213
income_2.0                                         0.0442      0.039      1.129      0.259      -0.033       0.121
income_3.0                                         0.0787      0.048      1.637      0.102      -0.016       0.173
income_missing                                     0.0860      0.150      0.573      0.567      -0.208       0.380
rate_spread_2.0                                    0.5917      0.037     15.941      0.000       0.519       0.665
rate_spread_3.0                                    1.1543      0.042     27.525      0.000       1.072       1.237
rate_spread_missing                                2.0686      0.596      3.471      0.001       0.900       3.238
hoepa_status_Not high cost                         2.5813      0.070     37.036      0.000       2.445       2.718
lien_status_Subordinate lien                       1.6251      0.144     11.282      0.000       1.343       1.908
applicant_credit_scoring_model_Experian FICO       0.0462      0.036      1.281      0.200      -0.025       0.117
applicant_credit_scoring_model_FICO Classic 04     0.0100      0.035      0.289      0.772      -0.058       0.078
total_loan_costs_2.0                               0.0307      0.053      0.579      0.563      -0.073       0.135
total_loan_costs_3.0                              -0.0095      0.079     -0.121      0.904      -0.164       0.145
total_loan_costs_missing                           2.6816      0.085     31.408      0.000       2.514       2.849
origination_charges_2.0                            0.0587      0.059      0.991      0.322      -0.057       0.175
origination_charges_3.0                           -0.0253      0.092     -0.275      0.783      -0.205       0.155
discount_points_2.0                                0.0783      0.058      1.362      0.174      -0.035       0.191
discount_points_3.0                                0.0323      0.088      0.365      0.715      -0.141       0.206
discount_points_missing                            0.3494      0.050      6.968      0.000       0.251       0.448
lender_credits_2.0                                 0.0882      0.077      1.140      0.255      -0.064       0.240
lender_credits_3.0                                 0.2377      0.077      3.079      0.002       0.086       0.389
lender_credits_missing                             0.1902      0.057      3.366      0.001       0.079       0.301
debt_to_income_ratio_30%-<36%                      0.1823      0.054      3.375      0.001       0.076       0.288
debt_to_income_ratio_36                            0.1701      0.077      2.210      0.027       0.019       0.321

with open("regression analysis output.txt", "w") as f:
    f.write(output.stdout)
    f.write(output.stderr)

In [11]:
print(
    'hello'
)

hello

In [1]:
df_tmp.info()

NameError: name 'df_tmp' is not defined

In [14]:
X.describe()

        const  Black African American
count  2872.0             2872.000000
mean      1.0                0.117688
std       0.0                0.322294
min       1.0                0.000000
25%       1.0                0.000000
50%       1.0                0.000000
75%       1.0                0.000000
max       1.0                1.000000

In [10]:
y.head()

106433    0
107460    0
126363    1
126375    0
126379    0
Name: denied, dtype: int64

In [15]:
df_tmp_psa.describe()

,loan_amount,income,combined_loan_to_value_ratio,loan_term,intro_rate_period,property_value,denied,Black African American
count,676.000000,670.000000,676.000000,676.000000,322.000000,6.760000e+02,676.000000,676.00000
mean,105399.408284,102.544776,47.351430,323.075444,1.257764,4.218787e+05,0.335799,0.50000
std,101984.691369,110.864197,23.457882,76.454074,4.625409,3.719246e+05,0.472619,0.50037
min,15000.000000,0.000000,3.000000,120.000000,1.000000,4.500000e+04,0.000000,0.00000
25%,45000.000000,46.000000,27.000000,360.000000,1.000000,2.050000e+05,0.000000,0.00000
50%,75000.000000,73.000000,48.000000,360.000000,1.000000,3.150000e+05,0.000000,0.50000
75%,125000.000000,118.000000,66.276250,360.000000,1.000000,5.350000e+05,1.000000,1.00000
max,965000.000000,1179.000000,152.754000,360.000000,84.000000,4.105000e+06,1.000000,1.00000

In [16]:
from utils import model as mod
import statsmodels.api as sm

# check separtion and remove those columns
flagged_variables = mod.find_separation_variables(
    df=df_tmp,
    target="denied",
    print_results=False,
    check_near_separation=True
)

In [17]:
flagged_variables

[]

In [18]:
df_tmp.drop(columns = flagged_variables, inplace = True)

In [19]:
df_tmp.shape

(2872, 14)

In [20]:
#############create woe
import toad

# Ensure object columns are clean strings
object_cols = df_tmp.select_dtypes(include=["object", "string"]).columns

for col in object_cols:
    df_tmp[col] = df_tmp[col].astype("string").fillna("__MISSING__")



# Create the combiner
combiner = toad.transform.Combiner()

# Fit bins 
combiner.fit(
    df_tmp,
    y='denied',
    method="chi",
    min_samples=0.05,
    empty_separate=True, #edit
    exclude= [group_i]   #['denied']
)

In [21]:
# Apply bin rules
df_tmp_bin = combiner.transform(df_tmp)

# convert bins to woe 
woe_transformer = toad.transform.WOETransformer()

df_tmp_woe = woe_transformer.fit_transform(
    df_tmp_bin,
    df_tmp_bin['denied'],
    exclude=['denied',group_i]
)

In [22]:
####### assign x and y data
y = df_tmp_woe["denied"]

# drop columns with single value. will end up being things like indicator for segment
df_tmp_woe = df_tmp_woe.loc[:, df_tmp_woe.nunique(dropna=False) > 1]

# reorder columns
col_order = df_tmp_woe.columns.tolist()
col_order.remove(group_i)
df_tmp_woe = df_tmp_woe[[group_i] + col_order]

X = sm.add_constant(df_tmp_woe.drop(columns='denied'))

In [24]:
model = sm.Logit(y, X)
result = model.fit()

print(result.summary())

# return result

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.558696
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                 denied   No. Observations:                 2872
Model:                          Logit   Df Residuals:                     2859
Method:                           MLE   Df Model:                           12
Date:                Tue, 15 Sep 2026   Pseudo R-squ.:                 0.05399
Time:                        14:41:16   Log-Likelihood:                -1604.6
converged:                      False   LL-Null:                       -1696.2
Covariance Type:            nonrobust   LLR p-value:                 9.566e-33
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                             -1.0306      0.766     -1.345      0.179      -2.532       0.471
Black African American             0.5188      0.128      4.068      0.000       0.269       0.769
occupancy_type                     1.3623      0.244      5.574      0.000       0.883       1.841
loan_amount                        0.8902      0.213      4.186      0.000       0.473       1.307
income                             1.6359      0.856      1.910      0.056      -0.042       3.314
lien_status                        0.5754      0.744      0.774      0.439      -0.882       2.033
loan_term                          0.4297      0.279      1.539      0.124      -0.117       0.977
intro_rate_period                 -1.2211      2.189     -0.558      0.577      -5.511       3.068
interest_only_payment            -55.7653   6281.862     -0.009      0.993   -1.24e+04    1.23e+04
property_value                     0.8946      0.123      7.263      0.000       0.653       1.136
open_end_line_of_credit           57.2020   6187.572      0.009      0.993   -1.21e+04    1.22e+04
business_or_commercial_purpose    -0.5707      0.387     -1.474      0.141      -1.330       0.188
row_id                             0.3933      0.761      0.517      0.605      -1.098       1.884
==================================================================================================

/home/jovyan/work/proj envs/fair-lend/lib/python3.13/site-packages/statsmodels/discrete/discrete_model.py:268: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  mlefit = super().fit(

def ols_dummy_run(df_tmp):
    import numpy as np
    import pandas as pd
    
    # df_tmp.info()
    
    # drop denied
    df_tmp.drop(columns=['action_taken'], inplace= True)
    
    # check unique values in characaters. we cant have too many and end up losing dfs
    
    def remove_high_cardinality_text_columns(df, max_cnt):
        """
        Remove object and string columns with more than max_cnt
        unique values.
    
        Returns:
            cleaned_df, unique_counts, removed_columns
        """
        text_cols = df.select_dtypes(
            include=["object", "str"]
        ).columns
    
        unique_counts = df[text_cols].nunique()
    
        removed_columns = unique_counts[
            unique_counts > max_cnt
        ].index.tolist()
    
        cleaned_df = df.drop(columns=removed_columns)
    
        return cleaned_df, unique_counts, removed_columns
    
    
    df_tmp, counts, removed = remove_high_cardinality_text_columns(
        df_tmp,
        max_cnt=20
    )
    
    # print(counts)
    print("Removed columns:", removed)
    
    
    
    # create bins for numerics
    
    
    import pandas as pd
    
    def qcut_numeric_columns(df, n_bins=5, exclude_cols=None):
        df = df.copy()
    
        if exclude_cols is None:
            exclude_cols = []
    
        numeric_cols = [
            col for col in df.select_dtypes(include="number").columns
            if col not in exclude_cols
        ]
    
        for col in numeric_cols:
            df[col] = (
                pd.qcut(
                    df[col],
                    q=n_bins,
                    labels=False,
                    duplicates="drop"
                )
                .add(1)
                .astype("object")
                .fillna("missing")
            )
    
        return df
    
    
    df_tmp = qcut_numeric_columns(
        df_tmp,
        n_bins=5,
        exclude_cols=["interest_rate", group_i]
    )
    
    
    
    # df_tmp.head()
    
    # df_tmp.info()
    
    
    
    # make dummy vars
    
    df_tmp = pd.get_dummies(
        df_tmp,
        columns=df_tmp.select_dtypes(exclude="number").columns,
        drop_first=True,
        dtype=int
    )
    
    df_tmp.shape
    
    ####### assign x and y data
    y = df_tmp["interest_rate"]
    
    # drop columns with single value. will end up being things like indicator for segment
    df_tmp = df_tmp.loc[:, df_tmp.nunique(dropna=False) > 1]
    

    
    
    
    # reorder columns
    col_order = df_tmp.columns.tolist()
    col_order.remove(group_i)
    df_tmp = df_tmp[[group_i] + col_order]
    
    X = sm.add_constant(df_tmp.drop(columns='interest_rate'))


    # Duplicate columns
    duplicate_cols = X.columns[X.T.duplicated()].tolist()
    print("Duplicate columns:", duplicate_cols)
    
    # Constant columns
    constant_cols = X.columns[X.nunique() <= 1].tolist()
    print("Constant columns:", constant_cols)
    
    # Matrix rank
    print("Number of columns:", X.shape[1])
    print("Matrix rank:", np.linalg.matrix_rank(X.to_numpy()))
    
    # do if duplicates then drop them
    
    if len(duplicate_cols) > 0:
        X = X.drop(columns=constant_cols + duplicate_cols)

    
    # drop high corr
    
    import numpy as np
    
    corr = X.corr().abs()
    
    upper = corr.where(
        np.triu(np.ones(corr.shape), k=1).astype(bool)
    )
    
    to_drop = [
        column
        for column in upper.columns
        if any(upper[column] > 0.95)
    ]
    
    X = X.drop(columns=to_drop)
    
    print("Dropped columns:", to_drop)
    
    
    
    
    
    
    model = sm.OLS(y, X)
    result = model.fit()
    
    # print(result.summary())

    return result

import numpy as np


def make_match_pair(df_tmp, target_to_exclude):
    
    from psmpy import PsmPy
    from psmpy.functions import cohenD
    # from psmpy.plotting import *
    
    # redo this but wit the pre woe data. need to redo woe before matched pair reg
    # df_tmp
    # df_tmp_woe
    
    
    # df_tmp_woe["row_id"] = df_tmp_woe.index
    df_tmp["row_id"] = df_tmp.index
    
    # df_tmp.head()
    
    # need to make dummies
    df_tmp_4psa = df_tmp
    
    
    
    exclude = [target_to_exclude, group_i, 'row_id']
    
    df_tmp_4psa = pd.concat(
        [
            df_tmp_4psa[exclude],
            pd.get_dummies(df_tmp_4psa.drop(columns=exclude), dtype=int)
        ],
        axis=1
    )
    
    
    
    
    # df_tmp_4psa.info()
    
    missing_columns = df_tmp_4psa.columns[df_tmp_4psa.isna().any()].tolist()
    missing_columns
    
    # target_to_exclude + missing_columns
    
    
    
    # psm = PsmPy(df_tmp_woe, treatment=group_i, indx='row_id', exclude = ['denied'])
    psm = PsmPy(df_tmp_4psa, treatment=group_i, indx='row_id', exclude = [target_to_exclude] + missing_columns)
    
    psm.logistic_ps(balance = True)
    
    psm.kdtree_matched(matcher='propensity_logit', replacement=False, caliper=None, drop_unmatched=True)
    
    # psm.df_matched
    
    # get unbinned attributes 
    # df_tmp_psa = pd.concat([], axis=1)
    df_tmp_psa = pd.DataFrame(psm.df_matched['row_id']).merge(df_tmp, on="row_id", how="left")
    df_tmp_psa.drop(columns='row_id', inplace = True)
    
    # df_tmp_psa.head()

    return df_tmp_psa



def logistic_woe_run(df_tmp):
    
    # check separtion and remove those columns
    flagged_variables = mod.find_separation_variables(
        df=df_tmp,
        target="denied",
        print_results=False,
        check_near_separation=True
    )
    
    df_tmp.drop(columns = flagged_variables, inplace = True)
    
    
    #############create woe
    import toad
    
    # Ensure object columns are clean strings
    object_cols = df_tmp.select_dtypes(include=["object", "string"]).columns
    
    for col in object_cols:
        df_tmp[col] = df_tmp[col].astype("string").fillna("__MISSING__")
    
    
    
    # Create the combiner
    combiner = toad.transform.Combiner()
    
    # Fit bins 
    combiner.fit(
        df_tmp,
        y='denied',
        method="chi",
        min_samples=0.05,
        exclude= [group_i]   #['denied']
    )
    
    # Apply bin rules
    df_tmp_bin = combiner.transform(df_tmp)
    
    # convert bins to woe 
    woe_transformer = toad.transform.WOETransformer()
    
    df_tmp_woe = woe_transformer.fit_transform(
        df_tmp_bin,
        df_tmp_bin['denied'],
        exclude=['denied',group_i]
    )
    
    
    ####### assign x and y data
    y = df_tmp_woe["denied"]
    
    # drop columns with single value. will end up being things like indicator for segment
    df_tmp_woe = df_tmp_woe.loc[:, df_tmp_woe.nunique(dropna=False) > 1]
    
    # reorder columns
    col_order = df_tmp_woe.columns.tolist()
    col_order.remove(group_i)
    df_tmp_woe = df_tmp_woe[[group_i] + col_order]
    
    X = sm.add_constant(df_tmp_woe.drop(columns='denied'))
   
    model = sm.Logit(y, X)
    result = model.fit()
    
    print(result.summary())

    return result